# Add the language switcher as global variable. Please note as the service is built as soon as twig is loaded, so
# this may not be applicable for services which are heavy to instantiate (you could use lazy services instead or
# use a Twig extension which takes care of loading the service lazily).
twig:
    globals:
        language_switcher: '@AppBundle\Templating\LanguageSwitcher'
